import type { ProjectContent } from "../types";

export const PROJECT_ITEMS: ProjectContent[] = [
  {
    kind: "project",
    id: "cortex",
    status: "published",
    createdAt: "2026-08-11",
    updatedAt: "2026-08-11",
    publishedAt: "2026-08-11",
    name: { cs: "Obchodní inteligence pro růst", en: "Business Intelligence for Growth" },
    tagline: {
      cs: "Systém pro vyhledávání příležitostí, analýzu trhu a práci s firemními daty. Pomáhá objevovat nové možnosti a zefektivnit obchodní procesy.",
      en: "A system for opportunity discovery, market analysis and working with business data. Helps uncover new possibilities and streamline business processes.",
    },
    badge: { cs: "Interní", en: "Internal" },
    category: { cs: "Interní systém", en: "Internal system" },
    tags: {
      cs: ["Automatizace", "Web scraping", "Data", "Výzkum"],
      en: ["Automation", "Web scraping", "Data", "Research"],
    },
    outcome: {
      cs: "Od manuálního vyhledávání k autonomnímu pipeline.",
      en: "From manual research to an autonomous pipeline.",
    },
    poster: "/images/posters/cortex.poster.jpg",
    href: "/projekty/cortex",
  },
  {
    kind: "project",
    id: "voice",
    status: "published",
    createdAt: "2026-08-11",
    updatedAt: "2026-08-11",
    publishedAt: "2026-08-11",
    name: { cs: "Inteligentní telefonní komunikace", en: "Intelligent Phone Communication" },
    tagline: {
      cs: "Moderní telefonní systém pro firmy. Vyřizování hovorů, rezervace schůzek, předávání informací a správa zákaznických požadavků kdykoliv.",
      en: "A modern phone system for businesses. Handling calls, booking meetings, sharing information and managing customer requests anytime.",
    },
    badge: { cs: "Demo", en: "Demo" },
    poster: "/images/posters/poster.voice.jpg",
    href: "/projekty/asistenti/voice",
  },
  {
    kind: "project",
    id: "chat",
    status: "published",
    createdAt: "2026-08-11",
    updatedAt: "2026-08-11",
    publishedAt: "2026-08-11",
    name: { cs: "Propojená komunikace napříč kanály", en: "Connected Communication Across Channels" },
    tagline: {
      cs: "Jednotná komunikační vrstva pro web, zprávy a další kontaktní body. Firmy zůstávají dostupné a zákazníci vždy najdou správnou cestu.",
      en: "A unified communication layer for web, messaging and other touchpoints. Businesses stay accessible and customers always find the right path.",
    },
    badge: { cs: "Demo", en: "Demo" },
    poster: "/images/posters/poster.chat.jpg",
    href: "/projekty/asistenti/chat",
  },
  {
    kind: "project",
    id: "zlaty-hreben",
    status: "published",
    createdAt: "2026-08-11",
    updatedAt: "2026-08-11",
    publishedAt: "2026-08-11",
    name: { cs: "Zlatý Hřeben", en: "Zlatý Hřeben" },
    tagline: {
      cs: "Prémiová webová prezentace pro barbershop. Design i vývoj.",
      en: "Premium barbershop website. Design and development.",
    },
    badge: { cs: "Case study", en: "Case study" },
    category: { cs: "Web Design / Development", en: "Web Design / Development" },
    tags: {
      cs: ["Next.js", "UX Design", "Web Development", "Vizuální identita"],
      en: ["Next.js", "UX Design", "Web Development", "Visual identity"],
    },
    poster: "/images/webs/screenshot.png",
    href: "/projekty/zlaty-hreben",
  },
  {
    kind: "project",
    id: "ponici",
    status: "published",
    createdAt: "2026-08-19",
    updatedAt: "2026-08-19",
    publishedAt: "2026-08-19",
    name: { cs: "Ponici.cz", en: "Ponici.cz" },
    tagline: {
      cs: "Digitální transformace jezdecké školy. Nový webový zážitek pro děti i dospělé, který převádí vztah ke koním, bezpečí a zkušenosti do moderní digitální platformy.",
      en: "Digital transformation of a riding school. A new web experience for children and adults that translates the bond with horses, safety and experience into a modern digital platform.",
    },
    badge: { cs: "Case study", en: "Case study" },
    category: { cs: "Web Design / Development", en: "Web Design / Development" },
    tags: {
      cs: ["UX Design", "Storytelling", "Next.js", "Web Development"],
      en: ["UX Design", "Storytelling", "Next.js", "Web Development"],
    },
    outcome: {
      cs: "Od informačního webu k digitálnímu zážitku.",
      en: "From an informational website to a digital experience.",
    },
    poster: "/images/ponici/ponici-home.png",
    href: "/projekty/ponici",
    liveHref: "https://ponici.cz",
  },
  {
    kind: "project",
    id: "youtube",
    status: "published",
    createdAt: "2026-08-11",
    updatedAt: "2026-08-11",
    publishedAt: "2026-08-11",
    name: { cs: "YouTube", en: "YouTube" },
    tagline: {
      cs: "Veřejná dokumentace vývoje, experimentů a launchů.",
      en: "Public documentation of development, experiments and launches.",
    },
    badge: { cs: "Kanál", en: "Channel" },
    poster: "/images/posters/notes.youtube.png",
    href: "/youtube",
  },
];
