import type { ProjectContent } from "../types";

export const PROJECT_ITEMS: ProjectContent[] = [
  {
    kind: "project",
    id: "cortex",
    status: "published",
    createdAt: "2026-08-11",
    updatedAt: "2026-08-11",
    publishedAt: "2026-08-11",
    name: { cs: "Cortex", en: "Cortex" },
    tagline: {
      cs: "Interní systém pro výzkum firem a evidence-based oslovení. Automatizace, která šetří hodiny denně.",
      en: "An internal system for company research and evidence-based outreach. Automation that saves hours every day.",
    },
    badge: { cs: "Interní", en: "Internal" },
    category: { cs: "Interní systém", en: "Internal system" },
    tags: {
      cs: ["AI", "Automatizace", "Web scraping", "Data"],
      en: ["AI", "Automation", "Web scraping", "Data"],
    },
    outcome: {
      cs: "Od manuálního vyhledávání k autonomnímu pipeline.",
      en: "From manual research to an autonomous pipeline.",
    },
    poster: "/images/posters/cortex.poster.jpg",
    href: "/cortex",
  },
  {
    kind: "project",
    id: "voice",
    status: "published",
    createdAt: "2026-08-11",
    updatedAt: "2026-08-11",
    publishedAt: "2026-08-11",
    name: { cs: "Telefonní systém", en: "Phone System" },
    tagline: {
      cs: "Telefonní komunikace. Hovory, rezervace termínů a odpovědi 24/7.",
      en: "Phone communication. Calls, appointment booking and answers 24/7.",
    },
    badge: { cs: "Demo", en: "Demo" },
    poster: "/images/posters/poster.voice.jpg",
    href: "/systems/communication/voice",
  },
  {
    kind: "project",
    id: "chat",
    status: "published",
    createdAt: "2026-08-11",
    updatedAt: "2026-08-11",
    publishedAt: "2026-08-11",
    name: { cs: "Kanálová komunikace", en: "Channel Communication" },
    tagline: {
      cs: "Komunikace pro web, WhatsApp a SMS. Jeden systém, více kanálů.",
      en: "Communication for web, WhatsApp and SMS. One system, many channels.",
    },
    badge: { cs: "Demo", en: "Demo" },
    poster: "/images/posters/poster.chat.jpg",
    href: "/systems/communication/chat",
  },
  {
    kind: "project",
    id: "zlaty-hreben",
    status: "published",
    createdAt: "2026-08-11",
    updatedAt: "2026-08-11",
    publishedAt: "2026-08-11",
    name: { cs: "Zlatý Hřeben", en: "Zlatý Hřeben" },
    tagline: {
      cs: "Prémiová webová prezentace pro barbershop. Design i vývoj.",
      en: "Premium barbershop website. Design and development.",
    },
    badge: { cs: "Case study", en: "Case study" },
    category: { cs: "Web Design / Development", en: "Web Design / Development" },
    tags: {
      cs: ["Next.js", "UX Design", "Web Development", "Vizuální identita"],
      en: ["Next.js", "UX Design", "Web Development", "Visual identity"],
    },
    poster: "/images/webs/screenshot.png",
    href: "/projekty/zlaty-hreben",
  },
  {
    kind: "project",
    id: "ponici",
    status: "published",
    createdAt: "2026-08-19",
    updatedAt: "2026-08-19",
    publishedAt: "2026-08-19",
    name: { cs: "Ponici.cz", en: "Ponici.cz" },
    tagline: {
      cs: "Digitální transformace jezdecké školy. Nový webový zážitek pro děti i dospělé, který převádí vztah ke koním, bezpečí a zkušenosti do moderní digitální platformy.",
      en: "Digital transformation of a riding school. A new web experience for children and adults that translates the bond with horses, safety and experience into a modern digital platform.",
    },
    badge: { cs: "Case study", en: "Case study" },
    category: { cs: "Web Design / Development", en: "Web Design / Development" },
    tags: {
      cs: ["UX Design", "Storytelling", "Next.js", "Web Development"],
      en: ["UX Design", "Storytelling", "Next.js", "Web Development"],
    },
    outcome: {
      cs: "Od informačního webu k digitálnímu zážitku.",
      en: "From an informational website to a digital experience.",
    },
    poster: "/images/ponici/ponici-home.png",
    href: "/projekty/ponici",
    liveHref: "https://ponici.cz",
  },
  {
    kind: "project",
    id: "youtube",
    status: "published",
    createdAt: "2026-08-11",
    updatedAt: "2026-08-11",
    publishedAt: "2026-08-11",
    name: { cs: "YouTube", en: "YouTube" },
    tagline: {
      cs: "Veřejná dokumentace vývoje, experimentů a launchů.",
      en: "Public documentation of development, experiments and launches.",
    },
    badge: { cs: "Kanál", en: "Channel" },
    poster: "/images/posters/notes.youtube.png",
    href: "/youtube",
  },
];
