import type { PageContent } from "../../types";

export const CORTEX_PAGE: PageContent<"cortex"> = {
  kind: "page",
  id: "cortex",
  slug: "cortex",
  status: "published",
  createdAt: "2026-08-11",
  updatedAt: "2026-08-11",
  publishedAt: "2026-08-11",
  seo: {
    title: {
      cs: "Obchodní inteligence pro růst",
      en: "Business Intelligence for Growth",
    },
    description: {
      cs: "Systém pro vyhledávání příležitostí, analýzu trhu a práci s firemními daty. Pomáhá objevovat nové možnosti a zefektivnit obchodní procesy.",
      en: "A system for opportunity discovery, market analysis and working with business data. Helps uncover new possibilities and streamline business processes.",
    },
  },
  data: {
    facts: [
      {
        label: { cs: "Role", en: "Role" },
        value: { cs: "Autor — interní systém", en: "Creator — internal system" },
      },
      {
        label: { cs: "Technologie", en: "Technology" },
        value: { cs: "Automatizace · Web scraping · Data", en: "Automation · Web scraping · Data" },
      },
      {
        label: { cs: "Výsledek", en: "Result" },
        value: { cs: "Interní systém v provozu", en: "Internal system in production" },
      },
      {
        label: { cs: "Živé", en: "Live" },
        value: { cs: "Soukromé", en: "Private" },
      },
    ],
    hero: {
      label: { cs: "Interní systém", en: "Internal System" },
      title: "Cortex",
      tagline: { cs: "Cortex nikdy nezačíná od technologie.", en: "Cortex never starts with technology." },
    },
    screenshot: {
      src: "/images/cortex/cortex-dashboard.png",
      alt: { cs: "Cortex dashboard", en: "Cortex dashboard" },
    },
    why: {
      label: { cs: "Proč", en: "Why" },
      text: {
        cs: "Tradiční oslovování vyžaduje hodiny manuální práce. Cortex ji automatizuje při zachování důkazně podložených doporučení.",
        en: "Traditional outreach requires hours of manual work. Cortex automates it while keeping every recommendation evidence-based.",
      },
    },
    chat: {
      cs: [
        { sender: "a", text: "Takže… co vlastně je Cortex?", delayMs: 500 },
        { sender: "b", text: "Můj interní systém.", delayMs: 1000 },
        { sender: "b", text: "Pomáhá mi rozhodnout, koho mám oslovit.", delayMs: 1200 },
        { sender: "a", text: "Takže… ChatGPT?", delayMs: 800 },
        { sender: "b", text: "Haha ne 😄", typingMs: 1200, delayMs: 600 },
        { sender: "b", text: "ChatGPT píše.", delayMs: 800 },
        { sender: "b", text: "Cortex rozhoduje, jestli vůbec něco má být napsáno.", delayMs: 1400 },
        { sender: "a", text: "Jak?", delayMs: 600 },
        { sender: "b", text: "Zkoumá firmy.", delayMs: 900 },
        { sender: "b", text: "Kontroluje weby.", delayMs: 700 },
        { sender: "b", text: "Hledá rezervační systémy.", delayMs: 800 },
        { sender: "b", text: "Sbírá důkazy.", delayMs: 900 },
        { sender: "a", text: "Takže jen prochází weby?", delayMs: 700 },
        { sender: "b", text: "Ne.", typingMs: 800, delayMs: 400 },
        { sender: "b", text: "Crawler jen sbírá informace.", delayMs: 1000 },
        { sender: "b", text: "Rozhodnutí dělá Cortex.", delayMs: 1200 },
        { sender: "a", text: "Co když si není jistej?", delayMs: 700 },
        { sender: "b", text: "Pak se nic nestane.", typingMs: 1500, delayMs: 600 },
        { sender: "a", text: "Fakt?", delayMs: 500 },
        { sender: "b", text: "Jo.", delayMs: 600 },
        { sender: "b", text: "Raději přijdu o potenciálního klienta…", delayMs: 1000 },
        { sender: "b", text: "…než abych poslal blbý e-mail.", delayMs: 1200 },
        { sender: "a", text: "Takže psaní e-mailů není to nejtěžší?", delayMs: 800 },
        { sender: "b", text: "Přesně.", typingMs: 2000, delayMs: 500 },
        { sender: "b", text: "Nejtěžší je rozhodnout, jestli vůbec má existovat.", delayMs: 1800 },
      ],
      en: [
        { sender: "a", text: "So… what actually is Cortex?", delayMs: 500 },
        { sender: "b", text: "It's my internal system.", delayMs: 1000 },
        { sender: "b", text: "It helps me decide who I should contact.", delayMs: 1200 },
        { sender: "a", text: "So… ChatGPT?", delayMs: 800 },
        { sender: "b", text: "Haha no 😄", typingMs: 1200, delayMs: 600 },
        { sender: "b", text: "ChatGPT writes.", delayMs: 800 },
        { sender: "b", text: "Cortex decides whether anything should be written at all.", delayMs: 1400 },
        { sender: "a", text: "How?", delayMs: 600 },
        { sender: "b", text: "It researches companies.", delayMs: 900 },
        { sender: "b", text: "Checks websites.", delayMs: 700 },
        { sender: "b", text: "Looks for booking systems.", delayMs: 800 },
        { sender: "b", text: "Collects evidence.", delayMs: 900 },
        { sender: "a", text: "So it just crawls websites?", delayMs: 700 },
        { sender: "b", text: "No.", typingMs: 800, delayMs: 400 },
        { sender: "b", text: "The crawler only gathers information.", delayMs: 1000 },
        { sender: "b", text: "Cortex makes the decision.", delayMs: 1200 },
        { sender: "a", text: "What if it isn't sure?", delayMs: 700 },
        { sender: "b", text: "Then nothing happens.", typingMs: 1500, delayMs: 600 },
        { sender: "a", text: "Seriously?", delayMs: 500 },
        { sender: "b", text: "Yep.", delayMs: 600 },
        { sender: "b", text: "I'd rather lose a potential client…", delayMs: 1000 },
        { sender: "b", text: "…than send a stupid email.", delayMs: 1200 },
        { sender: "a", text: "So writing emails isn't the hard part?", delayMs: 800 },
        { sender: "b", text: "Exactly.", typingMs: 2000, delayMs: 500 },
        { sender: "b", text: "The hardest part is deciding whether one should even exist.", delayMs: 1800 },
      ],
    },
    annotations: [
      { label: { cs: "Ověřené důkazy", en: "Verified evidence" }, note: { cs: "Více než 10 signálů potvrzeno", en: "More than 10 signals confirmed" }, appearAt: 0.2, top: "15%", left: "8%" },
      { label: { cs: "Skóre důvěry", en: "Confidence score" }, note: { cs: "94 %", en: "94 %" }, appearAt: 0.35, top: "55%", right: "10%" },
      { label: { cs: "Doporučení", en: "Recommendation" }, note: { cs: "Generováno z důkazů", en: "Generated from evidence" }, appearAt: 0.5, top: "35%", left: "55%" },
      { label: { cs: "Připraveno k revizi", en: "Ready for review" }, note: { cs: "Čeká na schválení", en: "Awaiting approval" }, appearAt: 0.65, top: "72%", left: "15%" },
      { label: { cs: "Příležitost", en: "Opportunity" }, note: { cs: "Detekována a ohodnocena", en: "Detected and scored" }, appearAt: 0.8, top: "20%", right: "18%" },
    ],
    confidence: {
      label: { cs: "Důvěra v rozhodnutí", en: "Confidence" },
      stages: [
        { label: { cs: "Počáteční analýza", en: "Initial analysis" }, desc: { cs: "Základní signály detekovány", en: "Basic signals detected" }, range: [0, 0.3] },
        { label: { cs: "Důkazy ověřeny", en: "Evidence verified" }, desc: { cs: "Křížová reference potvrdila nálezy", en: "Cross-referencing confirmed findings" }, range: [0.3, 0.6] },
        { label: { cs: "Připraveno k akci", en: "Ready for action" }, desc: { cs: "Všechny signály konzistentní", en: "All signals consistent" }, range: [0.6, 1] },
      ],
    },
    quoteSplit: {
      primary: { cs: "Systém píše.", en: "The system writes." },
      secondary: { cs: "Důkazy rozhodují.", en: "Evidence decides." },
    },
    editorial: {
      title: { cs: "Cortex umí doporučit nedělat nic.", en: "Cortex can recommend doing nothing." },
      text: { cs: "Cílem je správnost, ne prodej.", en: "The goal is correctness, not selling." },
    },
    cinematic: {
      label: { cs: "Právě probíhá", en: "In Progress" },
      steps: [
        { icon: "▶", label: { cs: "Důkazy", en: "Evidence" }, sub: { cs: "8 signálů shromážděno a ověřeno", en: "8 signals collected and verified" } },
        { icon: "▶", label: { cs: "Usuzování", en: "Reasoning" }, sub: { cs: "Analyzuje validovaný kontext", en: "Analyses validated context" } },
        { icon: "▶", label: { cs: "Rozhodnutí", en: "Decision" }, sub: { cs: "Nejvhodnější postup vybrán", en: "Most suitable action selected" } },
        { icon: "▶", label: { cs: "Generování", en: "Generation" }, sub: { cs: "Personalizované doporučení vytvořeno", en: "Personalised recommendation created" } },
        { icon: "✓", label: { cs: "Připraveno ke kontrole", en: "Ready for review" }, sub: { cs: "Čeká na manuální schválení", en: "Awaiting manual approval" } },
      ],
    },
    final: {
      title: [
        { cs: "Máte zájem o", en: "Interested in a similar" },
        { cs: "podobný interní systém?", en: "internal system?" },
      ],
      text: { cs: "Pojďme ho postavit společně.", en: "Let's build it together." },
      cta: { cs: "Pojďme stavět", en: "Let's build" },
    },
  },
};
